baseURL = 'https://LohitJ1729.github.io/'
locale = 'en-us'
title = 'Blog: Lohits Technical Notes'
theme = 'PaperMod'
tags = ["featured", "computer_vision", "graphics", "math", "probability", "machine_learning", "statistics", "geometry", "topology"]

[params]
  math = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
