baseURL = 'https://LohitJ1729.github.io/'
locale = 'en-us'
title = 'Lohit Jagarapu'
theme = 'PaperMod'
tags = ["featured", "computer_vision", "graphics", "math", "probability", "machine_learning", "statistics", "geometry", "topology", "RL"]

[params]
  math = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[params.assets]
  favicon32x32 = "/favicon-32x32.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
